### ISSUE TITLE
minAreaRect returns invalid theta

### ISSUE THREAD

**Issue by ashnair1** [mrlooi/maskrcnn-benchmark#11]
## ❓ Questions and Help
Hi. As the title suggests, I'm confused by cv2's minAreaRect returning invalid angles as theta. As I understand it, the `minAreaRect` outputs angles in the range of **[-90, 0)**. But I seem to be having issues with this assertion `assert -90 <= angle <= 0` because I'm getting positive angles (>0) and sometimes **-0.0**. Would you happen to have an idea as to why this is the case?

**Comment by mrlooi** [comment]
-0.0 = 0.0
This might help you https://stackoverflow.com/questions/15956124/minarearect-angles-unsure-about-the-angle-returned

**Comment by ruthvik92** [comment]
Try `pip install opencv-python==4.4.40` from `pip 20.2.3` or below.
