### ISSUE TITLE
Only one box detected per image 

### ISSUE THREAD

**Issue by binwangGit** [mrlooi/maskrcnn-benchmark#15]
## ❓ I trained this project on ICDAR.  And train loss converges to ~0.03, but only one box detected on per trainset image

**Comment by mrlooi** [comment]
That's odd, are you sure the ICDAR annotation is correct? 

Without further examples, I can't really provide a good suggestion

**Comment by Ivansyf34** [comment]
> ## ❓ I trained this project on ICDAR. And train loss converges to ~0.03, but only one box detected on per trainset image

I have the same question，do you solve it？
