### ISSUE TITLE
how to set the number of class?

### ISSUE THREAD

**Issue by ustczhouyu** [mrlooi/maskrcnn-benchmark#17]
## ❓ Questions and Help
Thank you for sharing the code. I would like to know, if there are 10 classes in my dataset, which parameters under which files do I need to change to 11? Looking forward to your reply, thank you @mrlooi

**Comment by mrlooi** [comment]
Hey, if you look at maskrcnn_benchmark/config/defaults.py, there's a field called `_C.MODEL.ROI_BOX_HEAD.NUM_CLASSES`. 
It's 81 by default (num COCO classes + 1 background class).
Add this to your .yaml config, and change the value to your num classes + 1 (for background class)

**Comment by ustczhouyu** [comment]
Thanks for your reply. I have set it up. Thank you again



| |
zhou19920226
|
|
邮箱：zhou19920226@126.com
|

Signature is customized by Netease Mail Master

On 01/19/2020 11:16, mrlooi wrote:

Hey, if you look at maskrcnn_benchmark/config/defaults.py, there's a field called _C.MODEL.ROI_BOX_HEAD.NUM_CLASSES.
It's 81 by default (num COCO classes + 1 background class).
Add this to your .yaml config, and change the value to your num classes + 1 (for background class)

**Comment by mrlooi** [comment]
Glad I could help, closing this issue

**Comment by ustczhouyu** [comment]
Hello, I want to know how to convert the test results of ICDAR into the format required by ICDAR15 for evaluation. Please help me, thank you！



| |
zhou19920226
|
|
邮箱：zhou19920226@126.com
|

Signature is customized by Netease Mail Master

On 01/19/2020 11:16, mrlooi wrote:

Hey, if you look at maskrcnn_benchmark/config/defaults.py, there's a field called _C.MODEL.ROI_BOX_HEAD.NUM_CLASSES.
It's 81 by default (num COCO classes + 1 background class).
Add this to your .yaml config, and change the value to your num classes + 1 (for background class)

**Comment by mrlooi** [comment]
I haven't tried icdar evaluation, they should have plenty of docs on that. Good luck!

**Comment by ustczhouyu** [comment]
Ok，thank you,I will try




| |
zhou19920226
|
|
邮箱：zhou19920226@126.com
|

Signature is customized by Netease Mail Master

On 01/23/2020 10:33, mrlooi wrote:

I haven't tried icdar evaluation, they should have plenty of docs on that. Good luck!
