### ISSUE TITLE
Where is the softnms file?

### ISSUE THREAD

**Issue by ustczhouyu** [mrlooi/maskrcnn-benchmark#28]
## ❓ Questions and Help
Hello, I only foundnms.h in maskrcnn_benchmark / csrc, but not soft nms. Where can I find soft nms? Thanks in advance.

**Comment by mrlooi** [comment]
soft_nms_cpu_kernel in https://github.com/mrlooi/rotated_maskrcnn/blob/master/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp
