### ISSUE TITLE
I don't fully understand the difference between RoI Align and rotated RoI Align

### ISSUE THREAD

**Issue by E-GM** [mrlooi/maskrcnn-benchmark#29]
## ❓ Questions and Help
Hey, @mrlooi , this is a good project, but I don not understand the difference RoI Align and rotated RoI Align, can you briefly introduce it? I will be very grateful. look forward to your reply.

**Comment by mrlooi** [comment]
RoI is axis aligned bounding box. Rotated RoI is rotated bounding box
Perhaps this link would help https://stackoverflow.com/questions/40404031/drawing-bounding-box-for-a-rotated-object
