### ISSUE TITLE
Annotation Tool

### ISSUE THREAD

**Issue by yashwant07** [mrlooi/maskrcnn-benchmark#37]
## ❓ Questions and Help

Can you suggest me a good annotation tool? where I can do annotations on my dataset and export it in the required format. (tool should be open source)

**Comment by mrlooi** [comment]
An annotation tool that supports polygons annotation is a good bet. Just google those, or "labelling for instance segmentation"

**Comment by yashwant07** [comment]
thanks, bro! but tell me one more thing if I don't want to use a rotated mask RCNN then which config file I can use for rotated bounding box not mask! or the format of annotation required for that...I really want to connect with you if you have any other platform where we can talk...

**Comment by mrlooi** [comment]
Simply turn off the instance segmentation options in the config, and it will default to just rotated bounding box. The annotation is still the same: Polygons. Internally the code generates rotated bounding boxes based on the polygons

**Comment by yashwant07** [comment]
thanks!
