### ISSUE TITLE
Is there any plan updating this work with Detectron2?

### ISSUE THREAD

**Issue by p890040** [mrlooi/maskrcnn-benchmark#38]
Hi.
I'm very impressive this work rotated maskrcnn, and indeed it performs very great in my customized dataset.
However, if it can works with Detectron2, I think the performance will be better.
So just wanna know if any plans:)

**Comment by mrlooi** [comment]
Hi, no plans for the foreseeable future unfortunately, not planning to maintain the repo. Plus I believe there is new research that can do this better (I hope! Have not kept up with instance segmentation)
