### ISSUE TITLE
train on my own dataset

### ISSUE THREAD

**Issue by andrewwyl** [mrlooi/maskrcnn-benchmark#4]
@mrlooi thanks for your great job,

i want to train fast_rcnn with rotated bboxs on my own datasets ,what should i do?

thanks

**Comment by mrlooi** [comment]
if you only want rotated bbox (without mask outputs), use configs/rotated/e2e_faster_rcnn...yaml.

If you want to train on your own dataset, the easiest way is to convert your dataset to COCO format, and add the dataset path to paths_catalog.py (see the original maskrcnn_benchmark repo README for more details, it's pretty straightforward)

Note: This repository generates the rotated bboxes automatically from mask polygons, so do make sure that your dataset has annotated mask polygons, and not just bounding box labels.

**Comment by mrlooi** [comment]
I've added these details to the README

**Comment by AidenFather** [comment]
> if you only want rotated bbox (without mask outputs), use configs/rotated/e2e_faster_rcnn...yaml.
> 
> If you want to train on your own dataset, the easiest way is to convert your dataset to COCO format, and add the dataset path to paths_catalog.py (see the original maskrcnn_benchmark repo README for more details, it's pretty straightforward)
> 
> Note: This repository generates the rotated bboxes automatically from mask polygons, so do make sure that your dataset has annotated mask polygons, and not just bounding box labels.

@mrlooi Can we use MSRA-TD500 dataset? Note that this includes cx, cy, w, h, a of bouding box. Thanks!
